### ISSUE TITLE
Videos fail to play

### ISSUE THREAD

**Issue by tjh1965** [HitkoDev/Videobox-Joomla#12]
I am having an issue with the videobox installation on one of my websites. The thumbnail loads fine, however the video does not play when you double click on the thumbnail. A black box loads, but no video.

![video-display-issue](https://cloud.githubusercontent.com/assets/16429659/17814640/6108d87e-65f6-11e6-8ec1-921fa9a18e81.jpg)

How do I fix this?

**Comment by HitkoDev** [comment]
It seems like your website is loading over HTTPS, but the player URL has plain HTTP therefore it's being blocked. I strongly recommend upgrading Videobox to a more recent version as this issue has already been fixed back in 2014 (Videobox 4). 

In a few days I'm going to issue a stable release of Videobox 5, and end the support for previous Videobox version. As you're already running the latest version of Joomla!, you shouldn't have much work updating Videobox.
