### ISSUE TITLE
HTML5 plugin crashes Joomla

### ISSUE THREAD

**Issue by rindvieh1234** [HitkoDev/Videobox-Joomla#13]
Hi,

when I enable the HTML plugin, my fresh Joomla installation seems to crash. I get server error 500. 
Maybe anything I missed to install?

kind regards

rindvieh

**Comment by HitkoDev** [comment]
Hello,

could you please provide some more info about the problem, i.e. what errors do you get in the error log, or do you get a similar error with other types of videos (YouTube, Vimeo, ...) as well?

If other videos don't work either, then the problem could be with the Videobox config, go to Plugins -> System - Videobox and make sure all settings are properly set.

**Comment by rindvieh1234** [comment]
Where can I find the error log?  Sorry I am new with Joomla, just installed it on my webspace.

**Comment by HitkoDev** [comment]
That depends on the server you're using. Here are some of the most common ones:
- wamp: C:\wamp\logs
- xampp: C:\xampp\php\logs\php_error_log
- Ubuntu / Debian: /var/log/apache2/error.log
- managed / shared hosting: look for error log icon on the control panel

Error log file may be specified in Joomla! admin: System -> System info -> PHP info -> error_log, however that value often isn't set.

**Comment by rindvieh1234** [comment]
Hi,

using a .user.ini I was able to get this error message:

> Parse error: syntax error, unexpected '[' in /hp/aa/ad/qb/www/riedochs.com/plugins/videobox/html5/html5.php on line 232

**Comment by HitkoDev** [comment]
It seems you're using PHP 5.3 or earlier, which doesn't support array dereferencing. PHP versions prior to 5.6 are no longer supported (see [PHP - supported versions](http://php.net/supported-versions.php)), so please update to a more recent version.
