### ISSUE TITLE
Shadowbox opens up way down on the page

### ISSUE THREAD

**Issue by vtpages** [HitkoDev/Videobox-Joomla#20]
Hi, using Videobox 5.0.0 rc2 and Joomla 3.5.1. Have a gallery page (with the plugin configured as follows: Multiple display = Gallery, Player Effect = Lightbox, 50 per page), but whenever I click on one of the video thumbnails, the lighbox opens up far down on the screen, requiring me to scroll down in order to watch the video. Website visitors won't even realize that it's down there. This is on Google Chrome and Firefox. Thanks for any help you can provide on bringing that lightbox further up the page!

**Comment by HitkoDev** [comment]
Update to the latest version, this has been fixed a while ago.
