### ISSUE TITLE
HTML5 Video Playback

### ISSUE THREAD

**Issue by Silkjazz** [HitkoDev/Videobox-Joomla#21]
Dear Hitko Support,

Thanks for the free videobox plugin for Joomla! My current settings are: Joomla 3.6.4 and PHP 5.6. on a live server.

The attached screenshots, with the syntax I've used, which displays the video I want to play from the videos directory on my site. But when I click on the play button of the video in the front end nothing happens. I tried youtube at that works fine. Could you tell me what I am doing wrong? 

I read on your site that “Videobox will try to convert local videos to HTML5 supported formats (requires avconv, and files in components/videobox/scripts/ have to be set as executable)”. If this is the problem how do I make the relevant files executable with an “avconv”? Additionally is “libav” something I have to enable or upload to a live server, which may not be possible on shared hosting. Can this be done a localhost for testing? I await your reply. 

Regards

SJ
![article content](https://cloud.githubusercontent.com/assets/23221026/19943546/2b4d82ac-a138-11e6-93ba-812c74c75b84.jpg)
![html5-video-front-end](https://cloud.githubusercontent.com/assets/23221026/19943547/2b500a90-a138-11e6-83e4-fcd58cb79064.jpg)

**Comment by HitkoDev** [comment]
Avconv / ffmpeg is a video conversion software, which has to be installed by the server admin. It's an experimental feature, and is intended for advanced users with good understanding of server software. The recommended way of doing this is to manually generate

```
core-balance.mp4
core-balance.ogv
core-balance.webm
core-balance.jpg
```

and upload these files to the server.
