### ISSUE TITLE
iss

### ISSUE THREAD

**Issue by jhoerlein** [HitkoDev/Videobox-Joomla#22]
Hello,

I’m attempting to use Videobox on a joomla website.   It displays the videos and the videos work correctly until I add any parameters.   What am I doing wrong?

Here’s my code:   ``` {videobox? &display=`box` &player=`vbinline` &pWidth='50'  &pHeight='50'  } m--28nqLRhaR5w|Transforming Planetary Consciousness - Aries 2015|,Q_ZcPOjVz7s|Transforming Planetary Consciousness - Pisces 2015|,8nPFnOe7ZF8|Transforming Planetary Consciousness - Sagittarius 2015{/videobox}```

I also sent you an email.    My email is jhoerlein@carolina.rr.com.  

Thanks.

**Comment by HitkoDev** [comment]
I think the problem is that you're using regular apostrophes instead of the grave accent for the `&pWidth` and `&pHeight` parameters - that's an unknown syntax, so the Videobox just ignores it.
