### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by VoReal** [HitkoDev/Videobox-Joomla#3]
I used the previous version of your cool Joomla extension and it worked like a charm - now that I updated to the latest version, the video displays have stopped working. When I checked the documentation available, I couldn't really find anything about the code snippets used to insert a videobox to an article (default in the previous version was "{videobox}{/videobox}" - doesn't seem to work for me anymore... has the way to insert a box changed in v5?) and where to edit it to change the snippet itself.
Is the previous version of your extension still available somewhere? I would like to downgrade back to the stable version since my site heavily depends on reliable video streams.

Thank you (also for a really useful extension!)

**Comment by HitkoDev** [comment]
The basic `{videobox}5AG4pQPdZoE|,ATod-zbwMDE|,BqHTJfxBRww|,S9M3WaZSTBk{/videobox}` syntax should still work, however the parameters syntax is now `{videobox? &player=`vbinline`}` (all values are escaped). There aren't many code snippets available right now as the syntax may change before the stable release. Basic syntax in v5 is
- `{videobox}videos{/videobox}`
- `{videobox? &param1=`value` &param2=`value`}videos{/videobox}`
- `{videobox@property-set-key}videos{/videobox}`
- `{videobox@property-set-key? &param1=`value` &param2=`value`}videos{/videobox}`

The `videos` syntax is the same as in previous versions. Please see https://github.com/HitkoDev/Videobox-Joomla/issues/1#issuecomment-206849257 and verify your configuration is correct. Various types of configuration (box, gallery, ...) have now been removed and replaced by property sets (in `System - Videobox` click `New set` to create a property set, or click an existing set to edit it). 

Current beta release doesn't contain the HTML5 adapter, so it won't work with local videos, but other than that it should work fine. 

If you need the latest 4.x version, you can get it [here](https://www.dropbox.com/s/c1k05ge1xwnkblk/pkg_videobox.zip).

**Comment by VoReal** [comment]
Thank you so much for this very interesting response. I really
appreciate the time you invest to keep up your good work. It's been my
favorite player solution so far cause it's so straightforward and easy
to use, almost easy enough to let certain users spice up their own
articles with video content (which is really great^^).

I'm gonna stick to v4 on my production site and will try out the beta on
my testing site. Thanks again for helping me out with the syntax ;)

Keep it up, dude! :)

**Comment by HitkoDev** [comment]
I'm closing this issue now, as most parts of the Videobox have been documented by now. If you feel like some important things are undocumented, feel free to reopen it and ask for more documentation.

**Comment by VoReal** [comment]
Thank you very much. I'll let you know in case I have any more questions
after reading it.

Cheers!
