### ISSUE TITLE
Feature: SoundCloud, continuous play

### ISSUE THREAD

**Issue by cmirnow** [HitkoDev/Videobox-Joomla#4]
Hello. I have one question ... it's probably more a question than a feature request. My client is dissatisfied, what  " you'll continue your listening experience with the next track or playlist on your Stream or profile" Soundcloud. Take a look links:

http://help.soundcloud.com/customer/en/portal/articles/2167086-continuous-play?b_id=9644
https://www.soundcloudcommunity.com/soundcloud/topics/playlist-playing-songs-i-dont-want-to-play

Tell me please, can Videobox solve this problem? I don't know, probably, this contradicts TOS Souncloud ? Or this possible?

**Comment by HitkoDev** [comment]
As far as I know, Continuous play only appears on the SoundClout website. When an embedded SoundCloud player finishes, it shows the **Play another track** suggestion, but doesn't play it automatically (see below). This is the behaviour you'll get from Videobox (unless SoundCloud changes their player, of course). 

![ss 2016-05-12 at 08 04 05](https://cloud.githubusercontent.com/assets/4700881/15225067/dc89a14e-187c-11e6-8762-3e526ccfb924.png)

### This doesn't mean changing it is impossible:

Removing the Play another track suggestion and other player modifications can be done by creating a custom player. There is a [library](https://github.com/soundcloud/soundcloud-custom-player/wiki) for a custom SoundCloud player. To use it with Videobox, you have to:
1. Change the `getPlayerLink` method in the SoundCloud adapter to return `index.php?vb-video=...`
2. Add the playerTpl filed to the soundcloud.xml
3. Implement the `renderVbPlayer($videobox)` method in the `Videobox/SoundCloud` plugin to output your custom player
4. Modify the playerTpl (include custom player JS library, define the layout and style, ...)

These things are already implemented in the HTML5 adapter, you can use it as a reference. Unfortunately I don't have enough time to implement and support these kinds of features, but I'll try to help should you have any questions regarding the custom player implementation.
