### ISSUE TITLE
Weird behavior, partly depending on browser

### ISSUE THREAD

**Issue by ghost** [HitkoDev/Videobox-Joomla#5]
Hi,
I'm testing Videobox with Twitch adapter on this side http://test.garde-division-germany.de/
The slider is not working correctly, I don't know where the two white bars left are coming from and in Firefox the player doesn't show any streams. In Chrome streams are being shown.
Can you tell me what I'am doing wrong or what the issue causes?

Thanks and regards,
Pingpong

**Comment by HitkoDev** [comment]
Could you provide some more details about the slider problem? When I try to open your link I get a TOO_MANY_REDIRECTS error so I'm unable to look into what's going on. (Or fix te link so I can see what's going on first-hand) 

Playing Twitch in Firefox goes a long way - just google 'twitch firefox not playing' and you'll get plenty of suggestions on what _could_ go wrong. Adding `&html5&quality=chunked` to the embedded URL seems to work in some cases, but only over plain http. Unfortunately it also breaks the player for https sites (regardless of the browser) so I can't use it. I'm waiting for Twitch to update their player, until then there's nothing I can do about it.

**Comment by ghost** [comment]
Hello,

I have tried to fix the redirect issue. Can you open the side now?
If not, can you provide me with the exact error message?

Am 21.06.2016 um 23:44 schrieb Hitko Development:

**Comment by HitkoDev** [comment]
The link works now. I can see the two white bars are a part of `<code>` element, so my guess is you've accidentally copied it together with the example code - in Joomla! click **Toggle editor** or **View source** to see plain HTML code, then remove the `<code>` and `</code>` and the white bars should go away.

I've also released a new version of Videobox for Joomla! with some significant performance improvements and bug fixes so I recommend you to update it.

**Comment by ghost** [comment]
Great, thank you very much. I don't know where this code was coming
from. I saw it in the source code but couldn't figure out why it is there.

I have updated the plugin.

When I click through the slider the channel logos change in size.
And on mouse over there is a long number being displayed. The same
number is also displayed under the video player. I don't know how to
remove this.

Am 22.06.2016 um 21:05 schrieb Hitko Development:

**Comment by HitkoDev** [comment]
That number you see on mouse over is the image file name. You have the SEOFLI plugin on your website, and what it does is (from SEOFLI documentation):
- Sets title attribute for links (generated from the linked text)
- Sets alt and title attribute for images (generated from the image name)

You can either re-order SEOFLI to run before Videobox (Admin -> Plugins -> SEOFLI -> ordering), or disable these features in SEOFLI settings.

HTML image elements have a constant width/height ratio, and the slider relies on that property when calculating the transition size. However one of the images is missing, and that messes up the sizing when you scroll past it. I think you have an extra bracket in your code near `https://www.twitch.tv/circon`, that could be the reason an image is missing.

**Comment by ghost** [comment]
Hello,

> HTML image elements have a constant width/height ratio, and the slider
> relies on that property when calculating the transition size. However
> one of the images is missing, and that messes up the sizing when you
> scroll past it. I think you have an extra bracket One of the images is
> missing, and it messes the width/height ratio when you scroll past it. I
> think you have an extra bracket in your code near
> |https://www.twitch.tv/circon|, that could be the reason an image is
> missing.

Which type of bracket are you talking about. I can't figure out where
the mistake is and I think all images are there.

Thanks and regards,

Marek

**Comment by HitkoDev** [comment]
In your code you have `|,https://www.twitch.tv/circon)|,` please remove the round bracket at the end.
