### ISSUE TITLE
gallery pagination doesn't work for me

### ISSUE THREAD

**Issue by tumbleweed95** [HitkoDev/Videobox-Joomla#7]
Hello,
Thank you for your work, I like your video gallery.
But I have a small problem and I don't know how to solve it.
The gallery pagination doesn't work for me

see in http://formation-joomla.bilobaweb.fr/portfolio/galerie-video-grille
I have 9 videos, 
in system videobox plugin, per page is set to 8
my code is : 
{videobox? &display=`gallery`}
RBJYyS6HS3w|Miles Davis - Freddie Freeloader|, 
Jb3lTVL7qM8|Melody Gardot - Same To You|,
xsDJp_dS-W8|Madeleine Peyroux - Don t Wait Too Long|,
PHdU5sHigYQ|Dave Brubeck - Take Five ( Original Video)|,
AnrzKBpKsq0|Jimmie Dale Gilmore - Mack The Knife|,
yLsqZfZ0ijg|Dave Brubeck-Unsquare Dance (1961)|,
vlVMISFl6lw|Philippe Jaroussky, voix haute|,
5qwa-A9qLk4|Louis Prima And Keely Smith- Enjoy Yourself|,
PVygjGoIUEE|Johnny Cash & Willie Nelson - Ghost Riders in the Sky|
{/videobox}

In advance, thank you for your answer
Best regards
Patrick

**Comment by HitkoDev** [comment]
I've tested the code below and it gives me 2 pages, the first containing 8 videos and the second one containing 1 video. Could you please test this code and tell me what you get?

```
{videobox? &display=`gallery` &perPage=`8`}
RBJYyS6HS3w|Miles Davis - Freddie Freeloader|,
Jb3lTVL7qM8|Melody Gardot - Same To You|,
xsDJp_dS-W8|Madeleine Peyroux - Don t Wait Too Long|,
PHdU5sHigYQ|Dave Brubeck - Take Five ( Original Video)|,
AnrzKBpKsq0|Jimmie Dale Gilmore - Mack The Knife|,
yLsqZfZ0ijg|Dave Brubeck-Unsquare Dance (1961)|,
vlVMISFl6lw|Philippe Jaroussky, voix haute|,
5qwa-A9qLk4|Louis Prima And Keely Smith- Enjoy Yourself|,
PVygjGoIUEE|Johnny Cash & Willie Nelson - Ghost Riders in the Sky
{/videobox}
```

**Comment by tumbleweed95** [comment]
Hello,
Thank you for your answer.
the problem comes from my template, with protostar, Pagination works well.
I do not know if there is a solution? http://formation-joomla.bilobaweb.fr/portfolio/galerie-video-grille#
regards
Patrick

**Comment by HitkoDev** [comment]
It looks like your template is trying to use AJAX dynamic pagination. For that to work, the videos would have to be stored in a separate database table, and Videobox would have to provide AJAX endpoints. That's only possible for a Joomla! component, which is not what Videobox has been made for.
