### ISSUE TITLE
Videobox update

### ISSUE THREAD

**Issue by danpdanp** [HitkoDev/Videobox-Joomla#8]
Hello,
I installed a long time in joomla 3.6.0 videobox 4.0.1 RC1 (april 2014).
In the "update site" is returned the following error message: "Can not update the site # 114", "URL: http://hitko.eu/files/software/videobox/updates.xml".
How do I update?
Thank you
![schermata 2016-07-13 alle 13 15 48](https://cloud.githubusercontent.com/assets/3397091/16801605/f9eafd96-48fb-11e6-8990-8da5ae278bcb.png)

**Comment by HitkoDev** [comment]
The update server for Videobox 4 has been shut down more than a year ago. In order to use it again, please manually install Videobox 5 package.
